project:
  type: website
  output-dir: docs

about:
  template: jolla
  image: images/myself.jpg

website:
  title: "Ivan Tse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



